# Mandatory Challenge
## Context
You work in the data analysis team of a very important company. On Monday, the company shares some good news with you: you just got hired by a major retail company! So, let's get prepared for a huge amount of work!

Then you get to work with your team and define the following tasks to perform:   
1. You need to start your analysis using data from the past.  
2. You need to define a process that takes your daily data as an input and integrates it.  

You are in charge of the second part, so you are provided with a sample file that you will have to read daily. To complete you task, you need the following aggregates:
* One aggregate per store that adds up the rest of the values.
* One aggregate per item that adds up the rest of the values.

You can import the dataset `retail_sales` from Ironhack's database. 

## Your task
Therefore, your process will consist of the following steps:
1. Read the sample file that a daily process will save in your folder. 
2. Clean up the data.
3. Create the aggregates.
4. Write three tables in your local database: 
    - A table for the cleaned data.
    - A table for the aggregate per store.
    - A table for the aggregate per item.

## Instructions
* Read the csv you can find in Ironhack's database.
* Clean the data and create the aggregates as you consider.
* Create the tables in your local database.
* Populate them with your process.

In [1]:
# your code here
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine

In [2]:
retail_sales = pd.read_csv('retail_sales.csv')

In [3]:
retail_sales.head(60)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2017,4,ROYAL WINE CORP,100200,GAMLA CAB - 750ML,WINE,0.0,1.0,0.0
1,2017,4,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.0,1.0,0.0
2,2017,4,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,0.0,8.0,0.0
3,2017,4,HEAVEN HILL DISTILLERIES INC,10120,J W DANT BOURBON 100P - 1.75L,LIQUOR,0.0,2.0,0.0
4,2017,4,ROYAL WINE CORP,101664,RAMON CORDOVA RIOJA - 750ML,WINE,0.0,4.0,0.0
5,2017,4,REPUBLIC NATIONAL DISTRIBUTING CO,101680,MANISCHEWITZ CREAM WH CONCORD - 1.5L,WINE,0.0,1.0,0.0
6,2017,4,ROYAL WINE CORP,101753,BARKAN CLASSIC PET SYR - 750ML,WINE,0.0,1.0,0.0
7,2017,4,JIM BEAM BRANDS CO,10197,KNOB CREEK BOURBON 9YR - 100P - 1.75L,LIQUOR,0.0,32.0,0.0
8,2017,4,STE MICHELLE WINE ESTATES,101974,CH ST MICH P/GRIS - 750ML,WINE,0.0,26.0,0.0
9,2017,4,MONSIEUR TOUTON SELECTION,102083,CH DE LA CHESNAIE MUSCADET - 750ML,WINE,0.0,1.0,0.0
10,2017,4,JIM BEAM BRANDS CO,10243,OLD GRAND DAD BOURBON 100P - 750ML,LIQUOR,0.0,3.0,0.0
11,2017,4,BACCHUS IMPORTERS LTD,10246,HILLROCK DOUBLE CASK RYE - 750ML,LIQUOR,0.0,5.0,0.0
12,2017,4,MHW LTD,10266,LA CHAYA MAL - 750ML,WINE,0.0,4.0,0.0
13,2017,4,MHW LTD,10268,LA CHAYA TORRONTES - 750ML,WINE,0.0,1.0,0.0
14,2017,4,CRAFT WINE & SPIRITS OF MARYLAND LLC,10269,FEW BOURBON - 750ML,LIQUOR,0.0,1.0,0.0
15,2017,4,CRAFT WINE & SPIRITS OF MARYLAND LLC,10270,KOPPER KETTLE WHISKEY - 750ML,LIQUOR,0.0,1.0,0.0
16,2017,4,ALLAGASH BREWING COMPANY,10271,ALLAGASH SAISON 6/4 NR 12.0Z,BEER,0.0,4.0,0.0
17,2017,4,REPUBLIC NATIONAL DISTRIBUTING CO,10274,KINSEY BOURBON - 750ML,LIQUOR,0.0,1.0,0.0
18,2017,4,PERNOD RICARD USA LLC,10275,LOT 40 RYE - 750ML,LIQUOR,0.0,1.0,0.0
19,2017,4,KATCEF BROTHERS INC,10306,TROEGS SOLID SENDER PALE ALE - 4/6NR,BEER,0.0,1.0,0.0
20,2017,4,BACARDI USA INC,10332,GREY GOOSE VODKA - 375ML,LIQUOR,0.0,11.0,0.0
21,2017,4,A VINTNERS SELECTIONS,103608,VAJRA LANGHE NEBBIOLO DOC - 750ML,WINE,0.0,1.0,0.0
22,2017,4,LEGENDS LTD,10370,BALTIMORE BEER WORKS DARK USHER - 4/6NR,BEER,0.0,1.0,0.0
23,2017,4,CASTLE BRANDS USA CORP,10375,PALLINI LIMONCELLO 6/CS - 750ML,LIQUOR,0.0,2.0,0.0
24,2017,4,Default,104,FOUR BOTTLE WINE TOTE,STR_SUPPLIES,0.0,2.0,0.0
25,2017,4,DIONYSOS IMPORTS INC,104060,LES CHAILLOUX SANCERRE CHERRIE - 750ML,WINE,0.0,1.0,0.0
26,2017,4,JACKSON FAMILY ENTERPRISES INC,10413,MURPHY GOODE CHARD - 750ML,WINE,0.0,22.0,0.0
27,2017,4,BUCK DISTRIBUTING COMPANY INC,10430,STONE IPA 4/6 NR - 12OZ,BEER,0.0,44.0,0.0
28,2017,4,PUNTO VINO LLC,104302,EREDI LODALI BAROLO 6/CS - 750ML,WINE,0.0,1.0,0.0
29,2017,4,KATCEF BROTHERS INC,10431,VICTORY GOLDEN MONKEY 4/6NR - 12OZ,BEER,0.0,25.0,0.0
30,2017,4,LEGENDS LTD,10434,LAGUNITAS IPA 4/6 NR - 12OZ,BEER,0.0,58.0,0.0
31,2017,4,LEGENDS LTD,10435,LAGUNITAS SUMPIN SUMPIN 4/6 NR - 12OZ,BEER,0.0,26.0,0.0
32,2017,4,LEGENDS LTD,10436,OSKAR BLUES DALES PALE ALE 12.OZ 4/6 CAN,BEER,0.0,31.0,0.0
33,2017,4,LEGENDS LTD,10437,CRISPIN CIDER ORIGINAL 4/6 NR - 12OZ,BEER,0.0,2.0,0.0
34,2017,4,LEGENDS LTD,10438,BRECKENRIDGE VANILLA PORTER 4/6 NR - 12OZ,BEER,0.0,6.0,0.0
35,2017,4,THE WINE GROUP,10439,CONCANNON FOUNDERS CAB - 750ML,WINE,0.0,3.0,0.0
36,2017,4,THE WINE GROUP,10441,LOVE P/NOIR - 750ML,WINE,0.0,16.0,0.0
37,2017,4,PERNOD RICARD USA LLC,10442,OLMECA ALTOS TEQ - PLATA - 750ML,LIQUOR,0.0,39.0,0.0
38,2017,4,PERNOD RICARD USA LLC,10443,OLMECA ALTOS TEQ - REPOSADO - 750ML,LIQUOR,0.0,20.0,0.0
39,2017,4,PERNOD RICARD USA LLC,10444,JAMESON IRISH WHISKY CASK MATES - 750ML,LIQUOR,0.0,3.0,0.0
40,2017,4,CRAFT WINE & SPIRITS OF MARYLAND LLC,10445,BRECKENRIDGE BOURBON - 750ML,LIQUOR,0.0,3.0,0.0
41,2017,4,ELITE WINES IMPORTS,104450,SEIFRIED S/BLC - 750ML,WINE,0.0,1.0,0.0
42,2017,4,PERNOD RICARD USA LLC,10472,MALIBU RUM - PASSION FRUIT - 750ML,LIQUOR,0.0,3.0,0.0
43,2017,4,BARON FRANCOIS LTD,10480,CHATEAU LAUBADE ARMAGNAC VSOP - 750ML,LIQUOR,0.0,2.0,0.0
44,2017,4,BARON FRANCOIS LTD,10499,CHATEAU LAUBADE ARMAGNAC XO - 750ML,LIQUOR,0.0,1.0,0.0
45,2017,4,PROXIMO SPIRITS INC,10529,JOSE CUERVO GOLDEN MARGARITA - 1.75L,LIQUOR,0.0,50.0,0.0
46,2017,4,PRESTIGE BEVERAGE GROUP OF MD LLC,105490,HAKUTSURU SAKE - 720ML,WINE,0.0,2.0,0.0
47,2017,4,KATCEF BROTHERS INC,1058,TROEGS HOPBACK ALE 4/6 NR - 12OZ,BEER,0.0,5.0,0.0
48,2017,4,Default,106,SIX BOTTLE WINE TOTE (NO LOGO),STR_SUPPLIES,0.0,2.0,0.0
49,2017,4,LEGENDS LTD,10609,FIRESTONE LUPONIC DISTORTION - 4/6 CAN 12.0Z,BEER,0.0,3.0,0.0
50,2017,4,LEGENDS LTD,10610,LAGUNITAS LIL SUMPIN - 2/12 NR 12.0Z,BEER,0.0,6.0,0.0
51,2017,4,DIAGEO NORTH AMERICA INC,10634,SMIRNOFF VODKA - CHERRY - 1L,LIQUOR,0.0,6.0,0.0
52,2017,4,JIM BEAM BRANDS CO,10636,HAKUSHU WHISKY 12 YR - 750ML,LIQUOR,0.0,6.0,0.0
53,2017,4,THE WINE GROUP,10637,CUPCAKE PROSECCO - 187 3PK,WINE,0.0,2.0,0.0
54,2017,4,LEGENDS LTD,10645,OSKAR BLUES DEVIANT DALES - 4/6 CAN 12.OZ,BEER,0.0,3.0,0.0
55,2017,4,JIM BEAM BRANDS CO,10666,SAUZA HORNITOS REPOSATO - 375ML,LIQUOR,0.0,1.0,0.0
56,2017,4,JIM BEAM BRANDS CO,10667,EFFEN VODKA - BLACK CHERRY - 375ML,LIQUOR,0.0,2.0,0.0
57,2017,4,JIM BEAM BRANDS CO,10668,MAKERS MARK BOURBON - 375ML,LIQUOR,0.0,27.0,0.0
58,2017,4,PRESTIGE BEVERAGE GROUP OF MD LLC,10673,CINNABON CINNAMON CREAM LIQ - 750ML,LIQUOR,0.0,1.0,0.0
59,2017,4,MOET HENNESSY USA,106739,VEUVE CLICQUOT DEMI SEC - 375ML,WINE,0.0,1.0,0.0

In [4]:
retail_sales.dtypes

YEAR                  int64
MONTH                 int64
SUPPLIER             object
ITEM CODE            object
ITEM DESCRIPTION     object
ITEM TYPE            object
RETAIL SALES        float64
RETAIL TRANSFERS    float64
WAREHOUSE SALES     float64
dtype: object

In [5]:
null_cols = retail_sales.isnull().sum()
null_cols

YEAR                 0
MONTH                0
SUPPLIER            24
ITEM CODE            0
ITEM DESCRIPTION     0
ITEM TYPE            1
RETAIL SALES         0
RETAIL TRANSFERS     0
WAREHOUSE SALES      0
dtype: int64

In [6]:
for col in retail_sales.columns: 
    print(col)

YEAR
MONTH
SUPPLIER
ITEM CODE
ITEM DESCRIPTION
ITEM TYPE
RETAIL SALES
RETAIL TRANSFERS
WAREHOUSE SALES

In [15]:
#So 'Store' is 'Supplier', so I need to aggregate by Supplier. Problematic, as values there are missing, so I'll drop them.
test = retail_sales.dropna(subset=['SUPPLIER'])
null_cols = test.isnull().sum()
null_cols

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           1
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [22]:
print(retail_sales.size)
print(retail_sales.shape)
print(test.size)
print(test.shape)

1155195
(128355, 9)
1154979
(128331, 9)

In [24]:
#Accepting the test, so will now make test the cleaned version
clean_retail_sales = test
clean_retail_sales.head()

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2017,4,ROYAL WINE CORP,100200,GAMLA CAB - 750ML,WINE,0.0,1.0,0.0
1,2017,4,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.0,1.0,0.0
2,2017,4,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,0.0,8.0,0.0
3,2017,4,HEAVEN HILL DISTILLERIES INC,10120,J W DANT BOURBON 100P - 1.75L,LIQUOR,0.0,2.0,0.0
4,2017,4,ROYAL WINE CORP,101664,RAMON CORDOVA RIOJA - 750ML,WINE,0.0,4.0,0.0

In [36]:
#Now to get aggregated data by supplier. Needs to become a new table, so make a new dataframe. 
store_sales = clean_retail_sales.groupby(['SUPPLIER'])['RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES' ].agg('sum').reset_index()
store_sales

,SUPPLIER,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,8 VINI INC,2.78,2.00,1.00
1,A HARDY USA LTD,0.40,0.00,0.00
2,A I G WINE & SPIRITS,12.52,5.92,134.00
3,A VINTNERS SELECTIONS,8640.57,8361.10,29776.67
4,A&E INC,11.52,2.00,0.00
...,...,...,...,...
328,WINEBOW INC,1.24,-1.58,0.00
329,YOUNG WON TRADING INC,1058.65,1047.40,2528.90
330,YUENGLING BREWERY,9628.35,10851.17,53805.32
331,Z WINE GALLERY IMPORTS LLC,8.83,11.25,16.00
332,ZURENA LLC,16.15,20.67,0.00

In [35]:
#And the items.
items = clean_retail_sales.groupby(['ITEM CODE'])['RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES' ].agg('sum').reset_index()
items

      ITEM CODE  RETAIL SALES  RETAIL TRANSFERS  WAREHOUSE SALES
0        100003          0.00              0.00             1.00
1        100007          0.00              0.00             1.00
2        100008          0.00              0.00             1.00
3        100009          0.00              0.00            12.00
4        100011          0.00              0.00             3.00
...         ...           ...               ...              ...
23548      9989          1.00              1.00             9.00
23549      9997        791.60            907.92          2384.05
23550     99970        118.24            118.00           456.00
23551     99988          0.00              0.00            70.00
23552     99990         68.50             90.00           985.50

[23553 rows x 4 columns]